### ISSUE TITLE
Tool Cache is failing the set-yt-dlp installation

### ISSUE THREAD

**Issue by VitalikL** [AnimMouse/setup-yt-dlp#1]
Hi @AnimMouse . Thank you for your great work!

I noticed that yt-dlp action started to fail relatively recently. I see that it is due to the failed step in the tools-cache

![Screen Shot 2024-10-08 at 10 49 38 AM](https://github.com/user-attachments/assets/3a8a5d3d-43ef-4bfd-9db5-139b9b4904af)

**Comment by AnimMouse** [comment]
> Thank you for your great work!

You're welcome!

> I noticed that yt-dlp action started to fail relatively recently. I see that it is due to the failed step in the tools-cache

It's 2024, and GitHub Actions still can't make their [type system](https://en.wikipedia.org/wiki/Type_system) right!
https://github.com/AnimMouse/setup-rclone/issues/10

**Comment by VitalikL** [comment]
@AnimMouse Thanks for the quick fix!

**Comment by AnimMouse** [comment]
@VitalikL You're welcome, and thank you so much for the Ko-fi donation!
