### ISSUE TITLE
Obsolete YouTube OAuth2 plugin

### ISSUE THREAD

**Issue by boulbi777** [AnimMouse/setup-yt-dlp#2]
Hi,

First of all, thank you for this great work.

I have recently noticed this error in my github action. Everything was working fine 2 weeks ago :

```
WARNING: The YouTube OAuth2 plugin is obsolete! Official support for logging into YouTube with OAuth in yt-dlp was added in the 2024.10.22 release. 
See  https://***.com/yt-dlp/yt-dlp/wiki/Extractors#logging-in-with-oauth  for how to use the official OAuth implementation.
To uninstall the plugin:
pip: pip uninstall yt-dlp-youtube-oauth2
pipx: pipx uninject yt-dlp yt-dlp-youtube-oauth2
manual: delete the plugin zip or files where you installed them
WARNING: [youtube:tab+oauth2] Incomplete yt initial data received. Retrying (1/3)...
WARNING: [youtube:tab+oauth2] Incomplete yt initial data received. Retrying (2/3)...
WARNING: [youtube:tab+oauth2] Incomplete yt initial data received. Retrying (3/3)...
WARNING: [youtube:tab+oauth2] Incomplete yt initial data received; please report this issue on  https://***.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
WARNING: [youtube:tab+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube:tab+oauth2] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube:tab+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube:tab+oauth2] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube:tab+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube:tab+oauth2] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube:tab+oauth2] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube:tab+oauth2] PLDBQmURq6pOfBKc6WU0wXTg2vxAjxjQel: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
```

Any idea on how to fix this ?

Thanks.

**Comment by AnimMouse** [comment]
Please update to `AnimMouse/setup-yt-dlp@v2` and follow the new installation guide [here](https://github.com/AnimMouse/setup-yt-dlp?tab=readme-ov-file#youtube-oauth).

**Comment by AnimMouse** [comment]
Sadly, it seems like YouTube created more restrictions with OAuth. https://github.com/yt-dlp/yt-dlp/issues/11462

**Comment by AnimMouse** [comment]
OAuth support has been removed in [v3](https://github.com/AnimMouse/setup-yt-dlp/releases/tag/v3), please use cookies instead.

**Comment by boulbi777** [comment]
Thank you for your response.
Cookies still does'nt work on Github Actions, I've been trying to configure them for a while...
Finally, I found that using VPN works really well, as Github runners IPs are generally flagged by Youtube.
Anyway, thanks for taking your time to answer this issue.

**Comment by AnimMouse** [comment]
> Thank you for your response.
> Anyway, thanks for taking your time to answer this issue.

You're welcome.

> Cookies still does'nt work on Github Actions, I've been trying to configure them for a while...

Cookies [works on my side](https://github.com/AnimMouse/setup-yt-dlp/actions/runs/12368008265), can you post your output here?

> Finally, I found that using VPN works really well, as Github runners IPs are generally flagged by Youtube.

True, I'm also using my own [IP space](https://as.215150.xyz) in order to bypass IP reputation problems.
